services:
  - type: web
    name: stadium-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/*
      - type: rewrite
        source: /assets/*
        destination: /assets/*
      - type: rewrite
        source: /manifest.json
        destination: /manifest.json
      - type: rewrite
        source: /favicon.ico
        destination: /favicon.ico
      - type: rewrite
        source: /*
        destination: /index.html
        spa: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://stadium-backend.onrender.com
      - key: REACT_APP_ENV
        value: production
    headers:
      # Cache static assets
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Don't cache HTML files
      - path: /*.html
        name: Cache-Control
        value: no-cache
      # Don't cache service worker
      - path: /service-worker.js
        name: Cache-Control
        value: no-cache
      # Default no-cache for other files
      - path: /*
        name: Cache-Control
        value: no-cache
